# OctoMap config

# Map topic, grid cell mininum resolution
topic: /occupied_cells_vis_array
resolution: 0.1
block_depth: 3 # Test-data octree depth (see Wang & Englot ICRA 2016)

# Sampling resolutions
free_resolution: 0.5 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Free/Occupied Thresholds
free_thresh: free_thresh
occupied_thresh: 0.7
var_thresh: 1000.0 # Threshold on variance to distinguish known/unknown
