# sim_unstructured config
num_class: 256
fx: 320.0
fy: 320.0
cx: 320.0
cy: 240.0
depth_scaling: 2000
topic: /semantic_map
dir: /media/ganlu/Samsung_T5/000_tro2020/tartanair-release1/abandonedfactory/Easy/P001/
semantic_img_folder: semantic_pred/
traversability_img_folder: traversability_pred/

# Information about range-finder data
scan_num: 399 # How many scans to use
max_range: 15 # Sensor max range (m)
#max_range: 30

# Bounds on map height
#min_z: 0
#max_z: 4.3

original_size: true
predict: false

block_depth: 2
ds_resolution: 0.1
free_resolution: 10.0
prior: 0.001
